var n1 = 10;
console.log(n1);
var b1 = true;
var b2 = false;
var b3;
console.log(b1);
console.log(b2);
var s1 = "you are the creater of your destiny";
var s2 = "powerfull people come from powerful places";
console.log(s1);
console.log(s2);
